"""
CSV export for the Baofeng DM-32UV CPS.

Column headers and value formats are taken directly from working codeplug
imports. Four files are generated:
    talk_groups.csv         — Talk Groups list (TX Contact references these by name)
    rx_group_lists.csv      — Digital RX Group Lists
    channels.csv            — Channels
    zones.csv               — Zones

Note: digital_contacts.csv (personal address book for private calls) is NOT
generated — the DM-32UV CPS uses Talk Groups.csv for group-call talkgroup
lookups, and digital_contacts.csv is only needed if you want a private-call
contact list (ham operators by DMR ID).  Talkgroup entries belong in Talk
Groups.csv, NOT digital_contacts.csv.
"""

import csv
import io
import zipfile
from .models import Channel, Codeplug, Contact, RXGroup, Zone


# ---------------------------------------------------------------------------
# Column definitions (exact header strings expected by DM-32UV CPS)
# ---------------------------------------------------------------------------

# Talk Groups: No., Name, ID, Type
# The Name field MUST exactly match the TX Contact field in channels.csv.
TALK_GROUP_HEADERS = ["No.", "Name", "ID", "Type"]

# Digital Contacts (personal address book) — NOT generated by default.
# Only needed if you want to store private-call ham operators.
CONTACTS_HEADERS = [
    "No.", "ID", "Repeater", "Name", "City", "Province", "Country",
    "Remark", "Type", "Alert Call",
]

# RX groups: No., Group Name, then Contact 1 … Contact 32
RX_GROUP_MAX_CONTACTS = 32
RX_GROUP_HEADERS = ["No.", "Group Name"] + [f"Contact {i+1}" for i in range(RX_GROUP_MAX_CONTACTS)]

CHANNEL_HEADERS = [
    "No.", "Channel Name", "Channel Type",
    "RX Frequency[MHz]", "TX Frequency[MHz]",
    "Power", "Band Width", "Scan List",
    "TX Admit", "Emergency System", "Squelch Level",
    "APRS Report Type", "Forbid TX", "APRS Receive",
    "Forbid Talkaround", "Auto Scan", "Lone Work",
    "Emergency Indicator", "Emergency ACK",
    "Analog APRS PTT Mode", "Digital APRS PTT Mode",
    "TX Contact", "RX Group List",
    "Color Code", "Time Slot",
    "Encryption", "Encryption ID", "APRS Report Channel",
    "Direct Dual Mode", "Private Confirm", "Short Data Confirm",
    "DMR ID",
    "CTC/DCS Decode", "CTC/DCS Encode",
    "Scramble", "RX Squelch Mode", "Signaling Type",
    "PTT ID", "VOX Function", "PTT ID Display",
]

ZONE_MAX_CHANNELS = 64
ZONE_HEADERS = ["No.", "Zone Name", "Channel Members"]


# ---------------------------------------------------------------------------
# Row builders
# ---------------------------------------------------------------------------

def _talk_group_row(no: int, c: Contact) -> list:
    """Row for Talk Groups.csv: No., Name, ID, Type."""
    return [no, c.name, c.dmr_id, c.call_type]


def _contact_row(no: int, c: Contact) -> list:
    return [no, c.dmr_id, "", c.name, "", "", "", c.call_type, 0, ""]


def _rx_group_row(no: int, g: RXGroup) -> list:
    row = [no, g.name]
    # Pad/truncate to exactly RX_GROUP_MAX_CONTACTS contact slots
    contacts = list(g.contacts[:RX_GROUP_MAX_CONTACTS])
    contacts += [""] * (RX_GROUP_MAX_CONTACTS - len(contacts))
    row.extend(contacts)
    return row


def _channel_row(no: int, ch: Channel) -> list:
    if ch.channel_type == "Digital":
        return _digital_channel_row(no, ch)
    else:
        return _analog_channel_row(no, ch)


def _digital_channel_row(no: int, ch: Channel) -> list:
    return [
        no,
        ch.name,
        "Digital",
        f"{ch.rx_freq:.5f}",
        f"{ch.tx_freq:.5f}",
        ch.power,
        "12.5KHz",
        "None",                         # Scan List
        ch.tx_admit,                    # Color Code Free / Always
        "None",                         # Emergency System
        ch.squelch,
        "Digital",                      # APRS Report Type
        0,                              # Forbid TX
        1,                              # APRS Receive
        0,                              # Forbid Talkaround
        0,                              # Auto Scan
        0,                              # Lone Work
        0,                              # Emergency Indicator
        0,                              # Emergency ACK
        0,                              # Analog APRS PTT Mode
        0,                              # Digital APRS PTT Mode
        ch.tx_contact,
        ch.rx_group,
        ch.color_code,
        f"Slot {ch.timeslot}",
        0,                              # Encryption
        "None",                         # Encryption ID
        1,                              # APRS Report Channel
        0,                              # Direct Dual Mode
        0,                              # Private Confirm
        0,                              # Short Data Confirm
        ch.dmr_id,
        "None",                         # CTC/DCS Decode
        "None",                         # CTC/DCS Encode
        "None",                         # Scramble
        "Carrier/CTC",                  # RX Squelch Mode
        "None",                         # Signaling Type
        "OFF",                          # PTT ID
        0,                              # VOX Function
        0,                              # PTT ID Display
    ]


def _analog_channel_row(no: int, ch: Channel) -> list:
    return [
        no,
        ch.name,
        "Analog",
        f"{ch.rx_freq:.5f}",
        f"{ch.tx_freq:.5f}",
        ch.power,
        "12.5KHz",
        "None",
        "Allow TX",
        "None",
        3,                              # Squelch
        "Off",                          # APRS Report Type
        0,
        0,                              # APRS Receive — off for analog
        0,                              # Forbid Talkaround
        0,
        0,
        0,
        0,
        0,
        0,
        "None",                         # TX Contact
        "None",                         # RX Group List
        0,                              # Color Code — unused for analog
        "Slot 1",
        0,
        "None",
        1,
        0,
        0,
        0,
        ch.dmr_id,
        ch.ctcss_decode,
        ch.ctcss_encode,
        "None",
        "Carrier/CTC",
        "None",
        "OFF",
        0,
        0,
    ]


def _zone_row(no: int, z: Zone) -> list:
    members = "|".join(z.channels[:ZONE_MAX_CHANNELS])
    return [no, z.name, members]


# ---------------------------------------------------------------------------
# Public export functions
# ---------------------------------------------------------------------------

def write_talk_groups_csv(codeplug: Codeplug) -> str:
    """Return Talk Groups.csv content (the file the CPS uses for TX Contact lookups)."""
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(TALK_GROUP_HEADERS)
    for i, c in enumerate(codeplug.contacts, 1):
        w.writerow(_talk_group_row(i, c))
    return buf.getvalue()


def write_contacts_csv(codeplug: Codeplug) -> str:
    """Return Digital Contacts.csv content (personal address book).  Not used by default."""
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(CONTACTS_HEADERS)
    for i, c in enumerate(codeplug.contacts, 1):
        w.writerow(_contact_row(i, c))
    return buf.getvalue()


def write_rx_groups_csv(codeplug: Codeplug) -> str:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(RX_GROUP_HEADERS)
    for i, g in enumerate(codeplug.rx_groups, 1):
        w.writerow(_rx_group_row(i, g))
    return buf.getvalue()


def write_channels_csv(codeplug: Codeplug) -> str:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(CHANNEL_HEADERS)
    for i, ch in enumerate(codeplug.channels, 1):
        w.writerow(_channel_row(i, ch))
    return buf.getvalue()


def write_zones_csv(codeplug: Codeplug) -> str:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(ZONE_HEADERS)
    for i, z in enumerate(codeplug.zones, 1):
        w.writerow(_zone_row(i, z))
    return buf.getvalue()


def write_zip(codeplug: Codeplug) -> bytes:
    """Return a ZIP archive containing all four CSV files."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("talk_groups.csv",      write_talk_groups_csv(codeplug))
        zf.writestr("rx_group_lists.csv",   write_rx_groups_csv(codeplug))
        zf.writestr("channels.csv",          write_channels_csv(codeplug))
        zf.writestr("zones.csv",             write_zones_csv(codeplug))
    return buf.getvalue()


def write_to_directory(codeplug: Codeplug, directory: str) -> None:
    """Write the four CSV files into a local directory."""
    import os
    os.makedirs(directory, exist_ok=True)
    files = {
        "talk_groups.csv":      write_talk_groups_csv(codeplug),
        "rx_group_lists.csv":   write_rx_groups_csv(codeplug),
        "channels.csv":          write_channels_csv(codeplug),
        "zones.csv":             write_zones_csv(codeplug),
    }
    for fname, content in files.items():
        path = os.path.join(directory, fname)
        with open(path, "w", newline="") as f:
            f.write(content)
        print(f"  Wrote {path}")
