"""
CSV export for the Baofeng DM-32UV CPS.

Column headers and value formats are taken directly from working codeplug
imports. Four files are generated:
    talk_groups.csv         — Talk Groups list (TX Contact references these by name)
    rx_group_lists.csv      — Digital RX Group Lists
    channels.csv            — Channels
    zones.csv               — Zones

Note: digital_contacts.csv (personal address book for private calls) is NOT
generated — the DM-32UV CPS uses Talk Groups.csv for group-call talkgroup
lookups, and digital_contacts.csv is only needed if you want a private-call
contact list (ham operators by DMR ID).  Talkgroup entries belong in Talk
Groups.csv, NOT digital_contacts.csv.
"""

import csv
import io
import zipfile
from .models import Channel, Codeplug, Contact, RXGroup, Zone


# ---------------------------------------------------------------------------
# Column definitions (exact header strings expected by DM-32UV CPS)
# ---------------------------------------------------------------------------

# Talk Groups: No., Name, ID, Type
# The Name field MUST exactly match the TX Contact field in channels.csv.
TALK_GROUP_HEADERS = ["No.", "Name", "ID", "Type"]

# Radio ID table.  The channel "DMR ID" column is a NAME reference into this
# table (it is not the numeric ID), so every name used by a channel must appear
# here or the CPS leaves the channel unbound.
DMR_ID_HEADERS = ["No.", "Radio ID", "Radio Name"]

# Digital Contacts (personal address book) — NOT generated by default.
# Only needed if you want to store private-call ham operators.
CONTACTS_HEADERS = [
    "No.", "ID", "Repeater", "Name", "City", "Province", "Country",
    "Remark", "Type", "Alert Call",
]

# RX groups: No., RX Group Name, Contact Members (pipe-separated — same pattern as zones)
# The CPS expects 3 columns, NOT one column per contact. The old 34-column format
# was wrong and caused import failures.
RX_GROUP_MAX_CONTACTS = 32
RX_GROUP_HEADERS = ["No.", "RX Group Name", "Contact Members"]

CHANNEL_HEADERS = [
    "No.", "Channel Name", "Channel Type",
    "RX Frequency[MHz]", "TX Frequency[MHz]",
    "Power", "Band Width", "Scan List",
    "TX Admit", "Emergency System", "Squelch Level",
    "APRS Report Type", "Forbid TX", "APRS Receive",
    "Forbid Talkaround", "Auto Scan", "Lone Work",
    "Emergency Indicator", "Emergency ACK",
    "Analog APRS PTT Mode", "Digital APRS PTT Mode",
    "TX Contact", "RX Group List",
    "Color Code", "Time Slot",
    "Encryption", "Encryption ID", "APRS Report Channel",
    "Direct Dual Mode", "Private Confirm", "Short Data Confirm",
    "DMR ID",
    "CTC/DCS Decode", "CTC/DCS Encode",
    "Scramble", "RX Squelch Mode", "Signaling Type",
    "PTT ID", "VOX Function", "PTT ID Display",
]

ZONE_MAX_CHANNELS = 64
ZONE_HEADERS = ["No.", "Zone Name", "Channel Members"]


# ---------------------------------------------------------------------------
# Row builders
# ---------------------------------------------------------------------------

def _talk_group_row(no: int, c: Contact) -> list:
    """Row for Talk Groups.csv: No., Name, ID, Type."""
    return [no, c.name, c.dmr_id, c.call_type]


def _contact_row(no: int, c: Contact) -> list:
    return [no, c.dmr_id, "", c.name, "", "", "", c.call_type, 0, ""]


def _rx_group_row(no: int, g: RXGroup) -> list:
    members = "|".join(g.contacts[:RX_GROUP_MAX_CONTACTS])
    return [no, g.name, members]


def _channel_row(no: int, ch: Channel) -> list:
    if ch.channel_type == "Digital":
        return _digital_channel_row(no, ch)
    else:
        return _analog_channel_row(no, ch)


def _digital_channel_row(no: int, ch: Channel) -> list:
    return [
        no,
        ch.name,
        "Digital",
        f"{ch.rx_freq:.5f}",
        f"{ch.tx_freq:.5f}",
        ch.power,
        "12.5KHz",
        "None",                         # Scan List
        ch.tx_admit,                    # Channel Idle / Allow TX
        "None",                         # Emergency System
        ch.squelch,
        "Digital",                      # APRS Report Type
        0,                              # Forbid TX
        1,                              # APRS Receive
        0,                              # Forbid Talkaround
        0,                              # Auto Scan
        0,                              # Lone Work
        0,                              # Emergency Indicator
        0,                              # Emergency ACK
        0,                              # Analog APRS PTT Mode
        0,                              # Digital APRS PTT Mode
        ch.tx_contact,
        ch.rx_group,
        ch.color_code,
        f"Slot {ch.timeslot}",
        0,                              # Encryption
        "None",                         # Encryption ID
        1,                              # APRS Report Channel
        0,                              # Direct Dual Mode
        0,                              # Private Confirm
        0,                              # Short Data Confirm
        ch.dmr_id,
        "None",                         # CTC/DCS Decode
        "None",                         # CTC/DCS Encode
        "None",                         # Scramble
        "Carrier/CTC",                  # RX Squelch Mode
        "None",                         # Signaling Type
        "OFF",                          # PTT ID
        0,                              # VOX Function
        0,                              # PTT ID Display
    ]


def _analog_channel_row(no: int, ch: Channel) -> list:
    return [
        no,
        ch.name,
        "Analog",
        f"{ch.rx_freq:.5f}",
        f"{ch.tx_freq:.5f}",
        ch.power,
        "25KHz",
        "None",
        "Allow TX",
        "None",
        3,                              # Squelch
        "Off",                          # APRS Report Type
        0,
        0,                              # APRS Receive — off for analog
        0,                              # Forbid Talkaround
        0,
        0,
        0,
        0,
        0,
        0,
        "None",                         # TX Contact
        "None",                         # RX Group List
        0,                              # Color Code — unused for analog
        "Slot 1",
        0,
        "None",
        1,
        0,
        0,
        0,
        ch.dmr_id,
        ch.ctcss_decode,
        ch.ctcss_encode,
        "None",
        "Carrier/CTC",
        "None",
        "OFF",
        0,
        0,
    ]


def _zone_row(no: int, z: Zone) -> list:
    members = "|".join(z.channels[:ZONE_MAX_CHANNELS])
    return [no, z.name, members]


# ---------------------------------------------------------------------------
# Public export functions
# ---------------------------------------------------------------------------

def write_talk_groups_csv(codeplug: Codeplug) -> str:
    """Return Talk Groups.csv content (the file the CPS uses for TX Contact lookups)."""
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(TALK_GROUP_HEADERS)
    for i, c in enumerate(codeplug.contacts, 1):
        w.writerow(_talk_group_row(i, c))
    return buf.getvalue()


def write_contacts_csv(codeplug: Codeplug) -> str:
    """Return Digital Contacts.csv content (personal address book).  Not used by default."""
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(CONTACTS_HEADERS)
    for i, c in enumerate(codeplug.contacts, 1):
        w.writerow(_contact_row(i, c))
    return buf.getvalue()


def write_dmr_id_csv(codeplug: Codeplug) -> str:
    """
    Return DMR-ID.csv content — the radio's own Radio ID table.

    A stock CPS document ships placeholder rows ("Radio 1", "Radio 2", ...).
    Channels reference a radio by *name*, so without this file every channel
    generated here points at a name the CPS has never heard of.
    """
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(DMR_ID_HEADERS)
    w.writerow([1, codeplug.radio_id, codeplug.radio_name])
    return buf.getvalue()


def write_rx_groups_csv(codeplug: Codeplug) -> str:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(RX_GROUP_HEADERS)
    for i, g in enumerate(codeplug.rx_groups, 1):
        w.writerow(_rx_group_row(i, g))
    return buf.getvalue()


def write_channels_csv(codeplug: Codeplug) -> str:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(CHANNEL_HEADERS)
    for i, ch in enumerate(codeplug.channels, 1):
        w.writerow(_channel_row(i, ch))
    return buf.getvalue()


def write_zones_csv(codeplug: Codeplug) -> str:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(ZONE_HEADERS)
    for i, z in enumerate(codeplug.zones, 1):
        w.writerow(_zone_row(i, z))
    return buf.getvalue()


def write_readme(codeplug: Codeplug) -> str:
    # Number the steps from the files actually shipped, so the list never
    # references a file that was omitted.
    import_as = {
        "dmr_id.csv":          'DMR ID  (or "Radio ID")',
        "talk_groups.csv":     "Talk Groups",
        "rx_group_lists.csv":  "Digital RX Group Lists",
        "channels.csv":        "Channels",
        "zones.csv":           "Zones",
    }
    order = [f for f in build_file_map(codeplug)]
    import_order = "\n".join(
        f"{i}. {name:<21} Import as: {import_as[name]}"
        for i, name in enumerate(order, 1)
    )
    return f"""\
CODEPLUGGER — DM-32UV Codeplug Import Instructions
====================================================

Import these files in the exact order below.  The CPS joins them by NAME, not
by row number, so a file imported out of order leaves everything that depends
on it pointing at nothing — TX Contact goes blank and zones fill up with
"Null Ch." entries.


IMPORT ORDER
------------
{import_order}


READ THIS IF YOU SEE "Null Ch."
--------------------------------
"Null Ch." means the CPS could not bind a channel, so the zone slot stayed
empty.  On this radio the usual cause is the Radio ID table.

The "DMR ID" column on every channel is a NAME pointing into the radio's
Radio ID list — it is not the numeric DMR ID.  A factory-fresh CPS document
has placeholder names there ("Radio 1", "Radio 2", ...), so a channel asking
for "{codeplug.radio_name}" matches nothing and never binds.

dmr_id.csv supplies that entry:

    No.,Radio ID,Radio Name
    1,{codeplug.radio_id},{codeplug.radio_name}

Import it FIRST.  If your CPS build has no DMR ID import option, open the
Radio ID / DMR ID list by hand and set entry 1 to:

    Radio ID:   {codeplug.radio_id}
    Radio Name: {codeplug.radio_name}

then re-import channels.csv and zones.csv.


FILE CONTENTS
-------------
dmr_id.csv
  Your radio's own DMR ID, and the name every channel references.

talk_groups.csv
  All talkgroups used by channels in this codeplug.  The TX Contact field on
  each channel references these entries by name — import this before
  channels.csv or every TX Contact will be blank.

channels.csv
  One channel per talkgroup per repeater, plus a Hotspot zone if selected.
  Each repeater zone includes an automatic TG 4000 Disconnect channel.

zones.csv
  One zone per repeater plus a Hotspot zone.  Zones reference channels by
  name, so channels.csv must be imported first.


RECOMMENDED CPS SETTINGS (Radio Settings tab)
----------------------------------------------
  GroupCall Match    Off   (hear all group calls on matching freq/CC/slot)
  PrivateCall Match  On    (only respond to calls addressed to your DMR ID)


NOTES
-----
- Parrot (TG 9990 / TG 310997) channels are set to Private Call type.
  Parrot will NOT respond if called as a Group Call.
- TG 4000 (Disconnect) disconnects the repeater from its current
  reflector or talkgroup.  Useful after a linked QSO.
- Verify all frequencies, offsets, and color codes against current
  repeater listings before transmitting.  Repeater data comes from
  RadioID.net and may not reflect recent changes.
- BrandMeister-verified repeaters were cross-checked against the
  BrandMeister device registry at time of generation.


----------------------------------------------------------------
TERMS OF USE / DISCLAIMER

By using this codeplug you acknowledge and agree to the following:

USE AT YOUR OWN RISK.  This software generates codeplug files based on
publicly available repeater data.  The generated files are provided "as
is" without warranty of any kind.

REVIEW REQUIRED.  You are solely responsible for carefully reviewing the
generated codeplug before importing it into your radio.  Verify
frequencies, offsets, color codes, talkgroups, and all other parameters.

NO LIABILITY.  You release James Dawdy (KQ9I), the website host, and any
related entity from any and all liability, claims, damages, or losses
arising from or related to the use of this software, the generated
codeplug files, or any damage to your radio or other equipment.

COMPLIANCE.  You are responsible for ensuring your radio programming
complies with all applicable laws, regulations, and license conditions
in your jurisdiction.

Generated by CODEPLUGGER — codeplugger.radio
© 2026 James Dawdy, KQ9I
----------------------------------------------------------------
"""


def build_file_map(codeplug: Codeplug) -> dict[str, str]:
    """
    Return {filename: content} in import order.

    rx_group_lists.csv is omitted when no RX groups were generated — importing
    a header-only file asks the CPS to apply an empty table, which is a
    pointless risk when there is nothing to apply.
    """
    files = {
        "dmr_id.csv":       write_dmr_id_csv(codeplug),
        "talk_groups.csv":  write_talk_groups_csv(codeplug),
    }
    if codeplug.rx_groups:
        files["rx_group_lists.csv"] = write_rx_groups_csv(codeplug)
    files["channels.csv"] = write_channels_csv(codeplug)
    files["zones.csv"]    = write_zones_csv(codeplug)
    return files


def write_zip(codeplug: Codeplug) -> bytes:
    """Return a ZIP archive containing the CSV files plus a README."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("README.txt", write_readme(codeplug))
        for fname, content in build_file_map(codeplug).items():
            zf.writestr(fname, content)
    return buf.getvalue()


def write_to_directory(codeplug: Codeplug, directory: str) -> None:
    """Write the CSV files into a local directory."""
    import os
    os.makedirs(directory, exist_ok=True)
    for fname, content in build_file_map(codeplug).items():
        path = os.path.join(directory, fname)
        with open(path, "w", newline="") as f:
            f.write(content)
        print(f"  Wrote {path}")
